sudo: required
services:
  - docker

before_install:
  - docker build -t raghu1/react-test -f ./client/Dockerfile.dev ./client


script:
  - docker run -e CI=true raghu1/react-test npm test -- --coverage

after_success:
  - docker build -t raghu1/multi-client .client
  - docker build -t raghu1/multi-nginx ./nginx
  - docker build -t raghu1/multi-worker ./worker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push raghu1/multi-client
  - docker push raghu1/multi-nginx
  - docker push raghu1/multi-worker
  - docker push raghu1/multi-server
deploy:
  provider : elasticbeanstalk
  region : us-east-1
  app: multi-docker
  env : Multidocker-env
  bucket_name: elasticbeanstalk-us-east-1-665716692154
  bucket_path: docker-multi
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY

