sudo: required
services:
  - docker

before_install:
  - docker build -t raghu1/react-test -f ./client/Dockerfile.dev ./client


script:
  - docker run -e CI=true raghu1/react-test npm test -- --coverage

after_success:
  - docker build -t raghu1/multi-client .client
  - docker build -t raghu1/multi-nginx ./nginx
  - docker build -t raghu1/multi-worker ./worker  

